"""Static layout definitions for the RX Engine (Phase 5A)."""

from __future__ import annotations

from dataclasses import dataclass

from app.response_experience.enums import ResponseComponent, ResponseLayoutType


@dataclass(frozen=True)
class LayoutDefinition:
    """Declarative presentation contract for one layout type."""

    layout_type: ResponseLayoutType
    title: str
    page_structure: tuple[str, ...]
    heading_hierarchy: tuple[str, ...]
    section_order: tuple[str, ...]
    preferred_components: tuple[ResponseComponent, ...]
    visual_emphasis: str
    expected_render_type: str


_LAYOUTS: dict[ResponseLayoutType, LayoutDefinition] = {
    ResponseLayoutType.DEFINITION: LayoutDefinition(
        layout_type=ResponseLayoutType.DEFINITION,
        title="Definition",
        page_structure=(
            "Title",
            "Executive Summary",
            "Definition",
            "Purpose",
            "Key Characteristics",
            "Important Notes",
            "Related Documents",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=(
            "definition",
            "purpose",
            "key_characteristics",
            "important_notes",
        ),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.DEFINITION,
            ResponseComponent.PURPOSE,
            ResponseComponent.KEY_CHARACTERISTICS,
            ResponseComponent.IMPORTANT_NOTES,
            ResponseComponent.RELATED_DOCUMENTS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="concise_definition",
        expected_render_type="definition_card",
    ),
    ResponseLayoutType.WORKFLOW: LayoutDefinition(
        layout_type=ResponseLayoutType.WORKFLOW,
        title="Workflow",
        page_structure=(
            "Title",
            "Executive Summary",
            "Objective",
            "Timeline",
            "Steps",
            "Roles",
            "Outcome",
            "Related Standards",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=(
            "objective",
            "timeline",
            "steps",
            "roles",
            "outcome",
        ),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.OBJECTIVE,
            ResponseComponent.TIMELINE,
            ResponseComponent.STEPS,
            ResponseComponent.RESPONSIBILITIES,
            ResponseComponent.OUTCOME,
            ResponseComponent.RELATED_STANDARDS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="sequential_timeline",
        expected_render_type="workflow_timeline",
    ),
    ResponseLayoutType.COMPARISON: LayoutDefinition(
        layout_type=ResponseLayoutType.COMPARISON,
        title="Comparison",
        page_structure=(
            "Title",
            "Summary",
            "Comparison Table",
            "Key Differences",
            "Recommendations",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=(
            "summary",
            "comparison_table",
            "key_differences",
            "recommendations",
        ),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.COMPARISON_TABLE,
            ResponseComponent.KEY_DIFFERENCES,
            ResponseComponent.RECOMMENDATIONS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="side_by_side_table",
        expected_render_type="comparison_table",
    ),
    ResponseLayoutType.HIERARCHY: LayoutDefinition(
        layout_type=ResponseLayoutType.HIERARCHY,
        title="Hierarchy",
        page_structure=(
            "Title",
            "Executive Summary",
            "Hierarchy",
            "Levels",
            "How it Supports Search",
            "Related Documents",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3", "h4"),
        section_order=("overview", "hierarchy_tree", "levels", "implications"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.HIERARCHY_TREE,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.RELATED_DOCUMENTS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="tree",
        expected_render_type="hierarchy_tree",
    ),
    ResponseLayoutType.POLICY: LayoutDefinition(
        layout_type=ResponseLayoutType.POLICY,
        title="Policy",
        page_structure=(
            "Title",
            "Purpose",
            "Scope",
            "Requirements",
            "Exceptions",
            "Responsibilities",
            "Governance",
            "Related Policies",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=(
            "purpose",
            "scope",
            "requirements",
            "exceptions",
            "responsibilities",
            "governance",
        ),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.PURPOSE,
            ResponseComponent.SCOPE,
            ResponseComponent.REQUIREMENTS,
            ResponseComponent.EXCEPTIONS,
            ResponseComponent.RESPONSIBILITIES,
            ResponseComponent.GOVERNANCE,
            ResponseComponent.OWNER,
            ResponseComponent.REVIEW_CYCLE,
            ResponseComponent.RELATED_POLICIES,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="requirements_first",
        expected_render_type="policy_sections",
    ),
    ResponseLayoutType.GOVERNANCE: LayoutDefinition(
        layout_type=ResponseLayoutType.GOVERNANCE,
        title="Governance",
        page_structure=(
            "Title",
            "Executive Summary",
            "Governance Context",
            "Bodies and Roles",
            "Authorities",
            "Escalation",
            "Related Documents",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=(
            "context",
            "bodies",
            "authorities",
            "escalation",
        ),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.GOVERNANCE,
            ResponseComponent.RESPONSIBILITIES,
            ResponseComponent.DECISION_MATRIX,
            ResponseComponent.RELATED_DOCUMENTS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="authority_structure",
        expected_render_type="governance_sections",
    ),
    ResponseLayoutType.RELATIONSHIP: LayoutDefinition(
        layout_type=ResponseLayoutType.RELATIONSHIP,
        title="Relationship",
        page_structure=(
            "Title",
            "Summary",
            "Concepts",
            "How They Relate",
            "Business Significance",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("concepts", "relationships", "significance"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.RELATIONSHIP_DIAGRAM,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.KEY_TAKEAWAYS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="relationship_links",
        expected_render_type="relationship_diagram",
    ),
    ResponseLayoutType.DECISION_GUIDANCE: LayoutDefinition(
        layout_type=ResponseLayoutType.DECISION_GUIDANCE,
        title="Decision Guidance",
        page_structure=(
            "Title",
            "Decision",
            "Criteria",
            "Recommended Path",
            "Constraints",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("decision", "criteria", "recommendation", "constraints"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.DECISION_MATRIX,
            ResponseComponent.RECOMMENDATIONS,
            ResponseComponent.IMPORTANT_NOTES,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="decision_path",
        expected_render_type="decision_matrix",
    ),
    ResponseLayoutType.TROUBLESHOOTING: LayoutDefinition(
        layout_type=ResponseLayoutType.TROUBLESHOOTING,
        title="Troubleshooting",
        page_structure=(
            "Title",
            "Problem",
            "Likely Causes",
            "Checks",
            "Escalation",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("problem", "causes", "checks", "escalation"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.WARNING,
            ResponseComponent.CHECKLIST,
            ResponseComponent.IMPORTANT_NOTES,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="action_checklist",
        expected_render_type="troubleshooting_checklist",
    ),
    ResponseLayoutType.REFERENCE_LOOKUP: LayoutDefinition(
        layout_type=ResponseLayoutType.REFERENCE_LOOKUP,
        title="Reference Lookup",
        page_structure=("Title", "Direct Answer", "Where it Appears", "Sources"),
        heading_hierarchy=("h1", "h2"),
        section_order=("answer", "location", "pointers"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.INFORMATION,
            ResponseComponent.RELATED_DOCUMENTS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="direct_answer",
        expected_render_type="reference_card",
    ),
    ResponseLayoutType.EXECUTIVE_SUMMARY: LayoutDefinition(
        layout_type=ResponseLayoutType.EXECUTIVE_SUMMARY,
        title="Executive Summary",
        page_structure=(
            "Title",
            "Executive Summary",
            "Key Takeaways",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("summary", "takeaways"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.KEY_TAKEAWAYS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="brief_executive",
        expected_render_type="executive_brief",
    ),
    ResponseLayoutType.EXECUTIVE_REPORT: LayoutDefinition(
        layout_type=ResponseLayoutType.EXECUTIVE_REPORT,
        title="Executive Report",
        page_structure=(
            "Title",
            "Executive Summary",
            "Key Takeaways",
            "Detailed Sections",
            "Related Documents",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=("summary", "takeaways", "details", "related"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.KEY_TAKEAWAYS,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.RELATED_DOCUMENTS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="long_form_report",
        expected_render_type="executive_report",
    ),
    ResponseLayoutType.COMPLIANCE: LayoutDefinition(
        layout_type=ResponseLayoutType.COMPLIANCE,
        title="Compliance",
        page_structure=(
            "Title",
            "Obligation",
            "Requirements",
            "Evidence Expected",
            "Related Policies",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("obligation", "requirements", "evidence"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.REQUIREMENTS,
            ResponseComponent.CHECKLIST,
            ResponseComponent.WARNING,
            ResponseComponent.FREQUENTLY_REFERENCED_POLICIES,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="obligation_checklist",
        expected_render_type="compliance_sections",
    ),
    ResponseLayoutType.LONG_REPORT: LayoutDefinition(
        layout_type=ResponseLayoutType.LONG_REPORT,
        title="Long Report",
        page_structure=(
            "Title",
            "Executive Summary",
            "Key Takeaways",
            "Detailed Sections",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2", "h3"),
        section_order=("summary", "takeaways", "details"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.KEY_TAKEAWAYS,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="long_form",
        expected_render_type="long_report",
    ),
    ResponseLayoutType.LIST_EXTRACTION: LayoutDefinition(
        layout_type=ResponseLayoutType.LIST_EXTRACTION,
        title="List",
        page_structure=(
            "Title",
            "Direct Answer List",
            "Item Descriptions",
            "Source Context",
            "Sources",
        ),
        heading_hierarchy=("h1", "h2"),
        section_order=("list", "descriptions", "context"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.DIRECT_LIST,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.INFORMATION,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="bulleted_list",
        expected_render_type="list_blocks",
    ),
    ResponseLayoutType.TIMELINE: LayoutDefinition(
        layout_type=ResponseLayoutType.TIMELINE,
        title="Timeline",
        page_structure=("Title", "Timeline", "Milestones", "Outcome", "Sources"),
        heading_hierarchy=("h1", "h2"),
        section_order=("timeline", "milestones", "outcome"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.TIMELINE,
            ResponseComponent.STEPS,
            ResponseComponent.OUTCOME,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="chronological",
        expected_render_type="timeline",
    ),
    ResponseLayoutType.TABLE_HEAVY: LayoutDefinition(
        layout_type=ResponseLayoutType.TABLE_HEAVY,
        title="Table",
        page_structure=("Title", "Summary", "Table", "Notes", "Sources"),
        heading_hierarchy=("h1", "h2"),
        section_order=("summary", "table", "notes"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.COMPARISON_TABLE,
            ResponseComponent.IMPORTANT_NOTES,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="primary_table",
        expected_render_type="table_primary",
    ),
    ResponseLayoutType.MIXED: LayoutDefinition(
        layout_type=ResponseLayoutType.MIXED,
        title="Mixed",
        page_structure=("Title", "Summary", "Details", "Sources"),
        heading_hierarchy=("h1", "h2"),
        section_order=("summary", "details"),
        preferred_components=(
            ResponseComponent.TITLE,
            ResponseComponent.EXECUTIVE_SUMMARY,
            ResponseComponent.DETAILED_SECTIONS,
            ResponseComponent.SOURCES,
        ),
        visual_emphasis="balanced",
        expected_render_type="mixed_sections",
    ),
}


def get_layout_definition(layout_type: ResponseLayoutType) -> LayoutDefinition:
    return _LAYOUTS[layout_type]


def all_layout_definitions() -> dict[ResponseLayoutType, LayoutDefinition]:
    return dict(_LAYOUTS)
